### ISSUE TITLE
Software serial support

### ISSUE THREAD

**Issue by rajesh-s** [electronut/arduino-bluey#2]
There is no Serial port for TX on the Bluey module other than the interface that connects to CP2104. Please add documentation/library modification needed for Software Serial on Bluey

**Comment by rishi-electronut** [comment]
nRF52 supports only one UART peripheral. This information can be found on their official [website](https://www.nordicsemi.com/eng/Products/Bluetooth-low-energy/nRF52832).

The only way you can use UART on custom pins is by disabling the UART on CP2104 pins 6 and 8 and configuring them to the pins of your choice.

This change can be made in arduino board file for Bluey.

**Comment by rajesh-s** [comment]
Thanks, I got a second Software Serial port working as a workaround to this issue.
